export const GET_EXPERIENCE_REQUEST = "GET_EXPERIENCE_REQUEST"
export const GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS"
export const GET_EXPERIENCE_FAIL = "GET_EXPERIENCE_FAIL"

export const CREATE_EXPERIENCE_REQUEST = "CREATE_EXPERIENCE_REQUEST"
export const CREATE_EXPERIENCE_SUCCESS = "CREATE_EXPERIENCE_SUCCESS"
export const CREATE_EXPERIENCE_FAIL = "CREATE_EXPERIENCE_FAIL"
export const EXPERIENCE_RESET = "EXPERIENCE_RESET"