export const GET_EXPERIENCE_REQUEST = "GET_EXPERIENCE_REQUEST"
export const GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS"
export const GET_EXPERIENCE_FAIL = "GET_EXPERIENCE_FAIL"

export const CREATE_EXPERIENCE_REQUEST = "CREATE_EXPERIENCE_REQUEST"
export const CREATE_EXPERIENCE_SUCCESS = "CREATE_EXPERIENCE_SUCCESS"
export const CREATE_EXPERIENCE_FAIL = "CREATE_EXPERIENCE_FAIL"
export const EXPERIENCE_RESET = "EXPERIENCE_RESET"

export const GET_EXPERIENCE_BYID_REQUEST = "GET_EXPERIENCE_BYID_REQUEST"
export const GET_EXPERIENCE_BYID_SUCCESS = "GET_EXPERIENCE_BYID_SUCCESS"
export const GET_EXPERIENCE_BYID_FAIL = "GET_EXPERIENCE_BYID_FAIL"

export const GET_EXPERIENCE_LOVE_REQUEST = "GET_EXPERIENCE_LOVE_REQUEST"
export const GET_EXPERIENCE_LOVE_SUCCESS = "GET_EXPERIENCE_LOVE_SUCCESS"
export const GET_EXPERIENCE_LOVE_FAIL = "GET_EXPERIENCE_LOVE_FAIL"

export const GET_EXPERIENCE_HAPPY_REQUEST = "GET_EXPERIENCE_HAPPY_REQUEST"
export const GET_EXPERIENCE_HAPPY_SUCCESS = "GET_EXPERIENCE_HAPPY_SUCCESS"
export const GET_EXPERIENCE_HAPPY_FAIL = "GET_EXPERIENCE_HAPPY_FAIL"

export const GET_EXPERIENCE_EMOTIONAL_REQUEST = "GET_EXPERIENCE_EMOTIONAL_REQUEST"
export const GET_EXPERIENCE_EMOTIONAL_SUCCESS = "GET_EXPERIENCE_EMOTIONAL_SUCCESS"
export const GET_EXPERIENCE_EMOTIONAL_FAIL = "GET_EXPERIENCE_EMOTIONAL_FAIL"

export const GET_EXPERIENCE_COMMENT_REQUEST = "GET_EXPERIENCE_COMMENT_REQUEST"
export const GET_EXPERIENCE_COMMENT_SUCCESS = "GET_EXPERIENCE_COMMENT_SUCCESS"
export const GET_EXPERIENCE_COMMENT_FAIL = "GET_EXPERIENCE_COMMENT_FAIL"
export const GET_EXPERIENCE_COMMENT_RESET = "GET_EXPERIENCE_COMMENT_RESET"
