export const CREATE_JOURNAL_REQUEST = "CREATE_JOURNAL_REQUEST"
export const CREATE_JOURNAL_SUCCESS = "CREATE_JOURNAL_SUCCESS"
export const CREATE_JOURNAL_FAIL = "CREATE_JOURNAL_FAIL"
export const CREATE_JOURNAL_RESET = "CREATE_JOURNAL_RESET"