export const GET_USER_REGISTER_REQUEST = "GET_USER_REGISTER_REQUEST"
export const GET_USER_REGISTER_SUCCESS = "GET_USER_REGISTER_SUCCESS"
export const GET_USER_REGISTER_FAIL = "GET_USER_REGISTER_FAIL"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"
export const GET_USER_RESET = "GET_USER_RESET"